backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          pattern: [".{60}", "Must have at least 60+ characters"],
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "string",
          hint: "Must be a Cloudinary image",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "LLL",
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "This will be shown in product page.",
        }
